# Dockerfile-nginx
FROM nginx:alpine

# Copier la configuration personnalisée de Nginx
COPY docker/nginx.prod.conf /etc/nginx/conf.d/default.conf

# Copier les assets statiques depuis le dossier public
COPY ../public /var/www/symfony/public

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
